### ISSUE TITLE
Apini mod doesn't load any content

### ISSUE THREAD

**Issue by TangyPango** [Jack7D1/Rimworld-Apini#105] opened 2021-08-01 15:19 UTC
Hello, I recently tried using the Apini Playable Race, Continued! mod from Steam but when I open RimWorld to play it, this message in red pops up:

Mod Apini Playable Race, Continued! did not load any content. Following load folders were used:
  - /Users/myname/Library/Application Support/Steam/steamapps/workshop/content/294100/2204437968/1.3\Expanded\E_SOS2
  - /Users/myname/Library/Application Support/Steam/steamapps/workshop/content/294100/2204437968/1.3\Patched\P_Rimbees
  - /Users/myname/Library/Application Support/Steam/steamapps/workshop/content/294100/2204437968/1.3\Patched\P_EPOE
  - /Users/myname/Library/Application Support/Steam/steamapps/workshop/content/294100/2204437968/Common
  - /Users/myname/Library/Application Support/Steam/steamapps/workshop/content/294100/2204437968/1.3\Common
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.LoadedModManager/<>c:<LoadModContent>b__13_1 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

When I tried to create a new colony, none of the Apini or Azuri scenarios would appear, none of the Apini related tabs or research were available and I am unable to create an Apini or Azuri pawn with a forked Prepare Carefully. I checked the folder (2204437968) where Apini was supposed to be and it looked like all the content was cownloaded, including the custom antennae and items. I manually deleted Apini from my mods folder and resubscribed on Steam but the same message would pop up. I did not have this issue before and was able to play as Apini in the past, even with the mods SOS2 and EPOE. Could this issue be related to the other mods listed in this debug log?

**Comment by Jack7D1** [comment] 2021-08-01 15:23
Hey thanks for writing this! You might have mismatched files. Go to "steamapps/workshop/294100"
And delete the folder named "2204437968"
Then verify game files for rimworld and wait for apini to be redownloaded.
Let me know if this fixed it!

**Comment by TangyPango** [comment] 2021-08-01 15:39
Thank you for the swift reply! Unfortunately, the issue still persists and the same debug message appeared after deleting and verifying the folder.

**Comment by Jack7D1** [comment] 2021-08-01 15:52
That is odd, I'm not able to reproduce this error using all mods that are currently supported by Apini, however I'm noticing another error with the CE patch. Seems an easy fix so I'll update it in a jiffy.

**Comment by Jack7D1** [comment] 2021-08-01 15:57
[apini.zip](https://github.com/Jack7D1/Rimworld-Apini/files/6912945/apini.zip)
try this copy of the mod! Load it with only its dependencies and official rimworld content.

**Comment by TangyPango** [comment] 2021-08-01 15:57
Ok, thank you so much for your help and effort!

**Comment by TangyPango** [comment] 2021-08-01 19:49
Hello once again. Unfortunately, the Apini mod still does not work for me despite using the previously mentioned technique and removing all other mods besides the dependencies. I greatly appreciate all the help you have provided and I thank you for your time and work you have put into this mod and the community.

**Comment by Jack7D1** [comment] 2021-08-01 19:53
Well thanks for that! I'd like to find out why it's not working... Could you make a hugslog of the error on a minimal modlist and link it here?

**Comment by TangyPango** [comment] 2021-08-01 20:26
Not sure if I did this correctly, but here it is.

https://gist.github.com/HugsLibRecordKeeper/ae81addbac13c9b6aae23e2577dbd6c6#file-output_log-txt

**Comment by Jack7D1** [comment] 2021-08-01 20:29
Oh are you running linux?

**Comment by TangyPango** [comment] 2021-08-01 20:29
No, I use Mac

**Comment by Jack7D1** [comment] 2021-08-01 20:30
Are you able to follow the file path of [Home_dir]/Library/Application Support/Steam/steamapps/workshop/content/294100/2204437968/Common? Does it exist?

**Comment by TangyPango** [comment] 2021-08-01 20:32
Yes, I am able to follow it and the folder has items in it (1.2, 1.3, About, Common, etc.)

**Comment by Jack7D1** [comment] 2021-08-01 20:34
Hmm, maybe MAC doesn't support backslashes, Try replacing the LoadFolders.xml with this!
[LoadFolders.zip](https://github.com/Jack7D1/Rimworld-Apini/files/6913374/LoadFolders.zip)

**Comment by TangyPango** [comment] 2021-08-01 20:45
Ok I will try it and let you know of anything new that happens

**Comment by TangyPango** [comment] 2021-08-01 20:51
I tried replacing the .xml folder with the .zip folder and started the game but the issue was not resolved.

**Comment by Jack7D1** [comment] 2021-08-01 20:57
Hugs log again?

**Comment by TangyPango** [comment] 2021-08-01 21:00
https://gist.github.com/f2e108c4aaaa294037a1536fb0aa60c8

**Comment by Jack7D1** [comment] 2021-08-01 21:15
Well, I'm stumped, all I can find online is https://ludeon.com/forums/index.php?topic=53857.0 and the thread just dies.

**Comment by TangyPango** [comment] 2021-08-01 21:58
It's fine. Thank you for helping me. I can really tell you have a strong passion for the mods you make.

**Comment by Jack7D1** [comment] 2021-08-02 02:08
It seems this is an issue with Rimworld for mac

**Comment by Jack7D1** [comment] 2021-08-02 23:29
Hey! Can you try and run this version? Folks on the forums suggest trying without the loadfolders system.
[apini.zip](https://github.com/Jack7D1/Rimworld-Apini/files/6920084/apini.zip)

**Comment by TangyPango** [comment] 2021-08-03 00:16
Sorry, I'm not exactly an advanced modder so I'm not sure how to disable the loadfolders system.

**Comment by Jack7D1** [comment] 2021-08-03 00:22
Oh! No don't worry I did it in that zip there!

**Comment by TangyPango** [comment] 2021-08-03 00:43
The issue is fixed. Thank you so much!

**Comment by Jack7D1** [comment] 2021-08-03 00:47
Closing note:
this issue was caused by Rimworld for mac not properly supporting Loadfolders. A no patches, no versioning copy of Apini will be available for mac users [here](https://github.com/Jack7D1/Rimworld-Apini/files/6920126/apini.zip) until this is fixed.

**Closed by Jack7D1** 2021-08-03 00:47 UTC
Labels: good first issue
